<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Customer;
use App\Models\Inventory;
use App\Models\Product;
use App\Models\ProductService;
use App\Models\Sale;
use App\Models\SaleItem;
use App\Models\User;
use App\Models\Warehouse;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class InvoiceSalesPaymentReportSeeder extends Seeder
{
    private const INVOICE_PREFIX = 'RPT-';

    public function run(): void
    {
        DB::transaction(function () {
            Sale::query()
                ->where('invoice_number', 'like', self::INVOICE_PREFIX . '%')
                ->delete();

            $warehouse = $this->warehouse();
            $users = $this->users();
            $customers = $this->customers();
            $products = $this->products($warehouse);
            $services = $this->services();

            foreach ($this->invoiceFixtures() as $index => $fixture) {
                $completedAt = Carbon::parse($fixture['completed_at']);
                $items = $this->resolveItems($fixture['items'], $products, $services);
                $subtotal = collect($items)->sum(fn ($item) => $item['unit_price'] * $item['quantity']);
                $discount = (float) ($fixture['discount_amount'] ?? 0);
                $tax = round(max($subtotal - $discount, 0) * ((float) ($fixture['tax_rate'] ?? 0) / 100), 2);
                $total = round($subtotal - $discount + $tax, 2);
                $paid = round((float) $fixture['paid_amount'], 2);

                $sale = Sale::create([
                    'invoice_number' => self::INVOICE_PREFIX . $completedAt->format('Ymd') . '-' . str_pad((string) ($index + 1), 4, '0', STR_PAD_LEFT),
                    'invoice_type' => $fixture['invoice_type'],
                    'customer_id' => $customers[$fixture['customer']]->id,
                    'warehouse_id' => $warehouse->id,
                    'user_id' => $users[$fixture['user']]->id,
                    'subtotal' => $subtotal,
                    'discount_amount' => $discount,
                    'tax_type' => $fixture['tax_type'] ?? 'exclusive',
                    'tax_rate' => $fixture['tax_rate'] ?? 0,
                    'tax_amount' => $tax,
                    'total_amount' => $total,
                    'paid_amount' => min($paid, $total),
                    'change_amount' => max($paid - $total, 0),
                    'payment_method' => $fixture['payment_method'],
                    'payment_terms' => $fixture['payment_terms'] ?? null,
                    'due_date' => $fixture['due_date'] ?? null,
                    'payment_status' => $fixture['payment_status'],
                    'status' => 'completed',
                    'notes' => 'Generated by InvoiceSalesPaymentReportSeeder for report testing.',
                    'completed_at' => $completedAt,
                    'created_at' => $completedAt,
                    'updated_at' => $completedAt,
                ]);

                foreach ($items as $item) {
                    SaleItem::create([
                        'sale_id' => $sale->id,
                        'product_id' => $item['product_id'],
                        'service_id' => $item['service_id'],
                        'item_type' => $item['item_type'],
                        'product_name' => $item['name'],
                        'product_sku' => $item['sku'],
                        'quantity' => $item['quantity'],
                        'unit_price' => $item['unit_price'],
                        'discount_amount' => 0,
                        'total_price' => $item['unit_price'] * $item['quantity'],
                        'cost_price' => $item['cost_price'],
                        'serial_numbers' => null,
                        'created_at' => $completedAt,
                        'updated_at' => $completedAt,
                    ]);
                }
            }
        });
    }

    private function warehouse(): Warehouse
    {
        return Warehouse::firstOrCreate(
            ['code' => 'RPT-MAIN'],
            [
                'name' => 'Report Testing Warehouse',
                'address' => 'Seeder demo location',
                'city' => 'Manila',
                'manager_name' => 'Report Manager',
                'phone' => '09170000000',
                'type' => 'main',
                'is_active' => true,
            ]
        );
    }

    private function users(): array
    {
        $password = Hash::make('password');

        return [
            'admin' => User::firstOrCreate(
                ['email' => 'reports.admin@example.test'],
                [
                    'name' => 'Reports Admin',
                    'password' => $password,
                    'role' => 'admin',
                    'is_active' => true,
                    'permissions' => User::getDefaultPermissions('admin'),
                ]
            ),
            'sales' => User::firstOrCreate(
                ['email' => 'reports.sales@example.test'],
                [
                    'name' => 'Reports Sales User',
                    'password' => $password,
                    'role' => 'cashier',
                    'is_active' => true,
                    'permissions' => array_values(array_unique([
                        ...User::getDefaultPermissions('cashier'),
                        'view_reports',
                    ])),
                ]
            ),
        ];
    }

    private function customers(): array
    {
        $records = [
            'hospital' => ['name' => 'Northcare Hospital', 'email' => 'billing@northcare.example.test', 'type' => 'corporate'],
            'clinic' => ['name' => 'Clinica San Isidro', 'email' => 'accounts@sanisidro.example.test', 'type' => 'corporate'],
            'walkin' => ['name' => 'Walk-in Customer', 'email' => 'walkin@example.test', 'type' => 'individual'],
            'laboratory' => ['name' => 'Precision Diagnostics Lab', 'email' => 'ap@precisionlab.example.test', 'type' => 'corporate'],
        ];

        return collect($records)
            ->map(fn ($record) => Customer::firstOrCreate(
                ['email' => $record['email']],
                [
                    'name' => $record['name'],
                    'phone' => '09171112222',
                    'address' => 'Report seed address',
                    'city' => 'Metro Manila',
                    'type' => $record['type'],
                    'credit_limit' => 250000,
                    'is_active' => true,
                ]
            ))
            ->all();
    }

    private function products(Warehouse $warehouse): array
    {
        $categories = [
            'equipment' => Category::firstOrCreate(['name' => 'Diagnostic Equipment'], ['description' => 'Report test category', 'sort_order' => 1, 'is_active' => true]),
            'supplies' => Category::firstOrCreate(['name' => 'Medical Supplies'], ['description' => 'Report test category', 'sort_order' => 2, 'is_active' => true]),
            'parts' => Category::firstOrCreate(['name' => 'Replacement Parts'], ['description' => 'Report test category', 'sort_order' => 3, 'is_active' => true]),
        ];

        $records = [
            'monitor' => ['category' => 'equipment', 'name' => 'Patient Monitor Pro 12', 'sku' => 'RPT-PMON-12', 'barcode' => '900000000001', 'cost' => 18500, 'price' => 28500],
            'pump' => ['category' => 'equipment', 'name' => 'Infusion Pump Compact', 'sku' => 'RPT-IPUMP-01', 'barcode' => '900000000002', 'cost' => 7200, 'price' => 11800],
            'gloves' => ['category' => 'supplies', 'name' => 'Nitrile Gloves Box', 'sku' => 'RPT-GLOVE-BOX', 'barcode' => '900000000003', 'cost' => 210, 'price' => 420],
            'filter' => ['category' => 'parts', 'name' => 'Nebulizer Filter Kit', 'sku' => 'RPT-NFILT-KIT', 'barcode' => '900000000004', 'cost' => 95, 'price' => 185],
        ];

        return collect($records)
            ->map(function ($record) use ($categories, $warehouse) {
                $product = Product::updateOrCreate(
                    ['sku' => $record['sku']],
                    [
                        'category_id' => $categories[$record['category']]->id,
                        'name' => $record['name'],
                        'slug' => Str::slug($record['name']),
                        'barcode' => $record['barcode'],
                        'cost_price' => $record['cost'],
                        'selling_price' => $record['price'],
                        'wholesale_price' => round($record['price'] * 0.9, 2),
                        'min_stock_level' => 5,
                        'max_stock_level' => 250,
                        'reorder_point' => 10,
                        'reorder_quantity' => 25,
                        'status' => 'active',
                    ]
                );

                Inventory::updateOrCreate(
                    ['product_id' => $product->id, 'warehouse_id' => $warehouse->id, 'product_variant_id' => null],
                    [
                        'quantity_on_hand' => 100,
                        'quantity_reserved' => 0,
                        'average_cost' => $record['cost'],
                        'location_legacy' => 'RPT-A1',
                        'last_counted_at' => Carbon::today(),
                    ]
                );

                return $product;
            })
            ->all();
    }

    private function services(): array
    {
        if (! Schema::hasTable('product_services')) {
            return [];
        }

        return [
            'calibration' => ProductService::updateOrCreate(
                ['code' => 'RPT-SVC-CAL'],
                ['name' => 'Equipment Calibration', 'slug' => 'equipment-calibration', 'price' => 2500, 'status' => 'active', 'notes' => 'Report test service']
            ),
            'installation' => ProductService::updateOrCreate(
                ['code' => 'RPT-SVC-INS'],
                ['name' => 'Installation Service', 'slug' => 'installation-service', 'price' => 3500, 'status' => 'active', 'notes' => 'Report test service']
            ),
        ];
    }

    private function invoiceFixtures(): array
    {
        $today = Carbon::today();

        return [
            [
                'completed_at' => $today->copy()->setTime(9, 15),
                'invoice_type' => 'sales',
                'customer' => 'hospital',
                'user' => 'sales',
                'payment_method' => 'cash',
                'payment_status' => 'paid',
                'paid_amount' => 28500,
                'items' => [['type' => 'product', 'key' => 'monitor', 'quantity' => 1]],
            ],
            [
                'completed_at' => $today->copy()->subDays(2)->setTime(14, 30),
                'invoice_type' => 'sales',
                'customer' => 'clinic',
                'user' => 'admin',
                'payment_method' => 'gcash',
                'payment_status' => 'paid',
                'paid_amount' => 14985.60,
                'discount_amount' => 100,
                'tax_rate' => 12,
                'items' => [
                    ['type' => 'product', 'key' => 'pump', 'quantity' => 1],
                    ['type' => 'product', 'key' => 'gloves', 'quantity' => 4],
                ],
            ],
            [
                'completed_at' => $today->copy()->subDays(8)->setTime(10, 5),
                'invoice_type' => 'service',
                'customer' => 'laboratory',
                'user' => 'sales',
                'payment_method' => 'card',
                'payment_status' => 'paid',
                'paid_amount' => 6000,
                'items' => [
                    ['type' => 'service', 'key' => 'calibration', 'quantity' => 1],
                    ['type' => 'service', 'key' => 'installation', 'quantity' => 1],
                ],
            ],
            [
                'completed_at' => $today->copy()->subDays(18)->setTime(16, 45),
                'invoice_type' => 'sales',
                'customer' => 'hospital',
                'user' => 'admin',
                'payment_method' => 'bank_transfer',
                'payment_status' => 'partial',
                'payment_terms' => 'Net 15',
                'due_date' => $today->copy()->subDays(3)->toDateString(),
                'paid_amount' => 20000,
                'items' => [
                    ['type' => 'product', 'key' => 'monitor', 'quantity' => 1],
                    ['type' => 'product', 'key' => 'filter', 'quantity' => 10],
                ],
            ],
            [
                'completed_at' => $today->copy()->subDays(35)->setTime(11, 20),
                'invoice_type' => 'sales',
                'customer' => 'clinic',
                'user' => 'sales',
                'payment_method' => 'terms',
                'payment_status' => 'unpaid',
                'payment_terms' => 'Net 30',
                'due_date' => $today->copy()->subDays(5)->toDateString(),
                'paid_amount' => 0,
                'items' => [
                    ['type' => 'product', 'key' => 'pump', 'quantity' => 2],
                    ['type' => 'product', 'key' => 'gloves', 'quantity' => 12],
                ],
            ],
            [
                'completed_at' => $today->copy()->subMonths(2)->setTime(13, 0),
                'invoice_type' => 'sales',
                'customer' => 'walkin',
                'user' => 'sales',
                'payment_method' => 'paymaya',
                'payment_status' => 'paid',
                'paid_amount' => 1850,
                'items' => [['type' => 'product', 'key' => 'filter', 'quantity' => 10]],
            ],
            [
                'completed_at' => $today->copy()->subMonths(4)->setTime(15, 10),
                'invoice_type' => 'service',
                'customer' => 'laboratory',
                'user' => 'admin',
                'payment_method' => 'terms',
                'payment_status' => 'unpaid',
                'payment_terms' => 'Due on receipt',
                'due_date' => $today->copy()->subMonths(4)->addDays(7)->toDateString(),
                'paid_amount' => 0,
                'items' => [['type' => 'service', 'key' => 'calibration', 'quantity' => 3]],
            ],
            [
                'completed_at' => $today->copy()->subYear()->addDays(14)->setTime(10, 40),
                'invoice_type' => 'sales',
                'customer' => 'hospital',
                'user' => 'admin',
                'payment_method' => 'cash',
                'payment_status' => 'paid',
                'paid_amount' => 57000,
                'items' => [['type' => 'product', 'key' => 'monitor', 'quantity' => 2]],
            ],
        ];
    }

    private function resolveItems(array $fixtureItems, array $products, array $services): array
    {
        return collect($fixtureItems)
            ->map(function ($item) use ($products, $services) {
                if ($item['type'] === 'service' && isset($services[$item['key']])) {
                    $service = $services[$item['key']];

                    return [
                        'product_id' => null,
                        'service_id' => $service->id,
                        'item_type' => 'service',
                        'name' => $service->name,
                        'sku' => $service->code,
                        'quantity' => $item['quantity'],
                        'unit_price' => (float) $service->price,
                        'cost_price' => 0,
                    ];
                }

                $product = $products[$item['key']];

                return [
                    'product_id' => $product->id,
                    'service_id' => null,
                    'item_type' => 'product',
                    'name' => $product->name,
                    'sku' => $product->sku,
                    'quantity' => $item['quantity'],
                    'unit_price' => (float) $product->selling_price,
                    'cost_price' => (float) $product->cost_price,
                ];
            })
            ->all();
    }
}
