<?php

namespace App\Support;

use App\Models\SystemSetting;

class PrintDocumentSettings
{
    public static function for(string $documentType): array
    {
        return array_replace_recursive(
            self::defaults($documentType),
            SystemSetting::get(self::key($documentType), [])
        );
    }

    public static function save(string $documentType, array $settings): void
    {
        SystemSetting::set(self::key($documentType), self::normalize($settings), 'json');
    }

    public static function defaults(string $documentType): array
    {
        $title = $documentType === 'purchase_order' ? 'PURCHASE ORDER' : 'SALES INVOICE';

        return [
            'document_type' => $documentType,
            'header' => [
                'height' => 130,
                'logos' => [],
                'title' => $title,
                'subtitle' => '',
                'show_company_details' => true,
            ],
            'footer' => [
                'enabled' => true,
                'text' => 'Generated by ' . config('app.name'),
                'layout' => 'horizontal',
                'columns' => 4,
                'signatories' => [
                    ['label' => 'Prepared By', 'name' => '', 'title' => ''],
                    ['label' => 'Checked By', 'name' => '', 'title' => ''],
                    ['label' => 'Approved By', 'name' => '', 'title' => ''],
                    ['label' => 'Received By', 'name' => '', 'title' => ''],
                ],
            ],
        ];
    }

    public static function logoUrl(array $logo): ?string
    {
        if (empty($logo['path'])) {
            return null;
        }

        return asset('storage/' . ltrim($logo['path'], '/'));
    }

    private static function key(string $documentType): string
    {
        return 'print_layout.' . $documentType;
    }

    private static function normalize(array $settings): array
    {
        $settings['header']['height'] = max(80, min(260, (int) ($settings['header']['height'] ?? 130)));
        $settings['footer']['columns'] = max(1, min(6, (int) ($settings['footer']['columns'] ?? 4)));
        $settings['footer']['layout'] = in_array($settings['footer']['layout'] ?? 'horizontal', ['horizontal', 'vertical'], true)
            ? $settings['footer']['layout']
            : 'horizontal';

        $settings['header']['logos'] = array_values(array_map(function ($logo) {
            return [
                'id' => $logo['id'] ?? uniqid('logo_', true),
                'path' => $logo['path'] ?? '',
                'label' => $logo['label'] ?? 'Logo',
                'x' => max(0, min(100, (float) ($logo['x'] ?? 0))),
                'y' => max(0, min(100, (float) ($logo['y'] ?? 0))),
                'width' => max(30, min(240, (int) ($logo['width'] ?? 90))),
            ];
        }, $settings['header']['logos'] ?? []));

        $settings['footer']['signatories'] = array_values(array_map(function ($signatory) {
            return [
                'label' => $signatory['label'] ?? '',
                'name' => $signatory['name'] ?? '',
                'title' => $signatory['title'] ?? '',
            ];
        }, $settings['footer']['signatories'] ?? []));

        return $settings;
    }
}
